# Generated by Django 4.0.3 on 2022-03-12 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='main.destinations'),
        ),
    ]
